### ISSUE TITLE
ToDoList插件创建与修改问题

### ISSUE THREAD

**Issue by ghost** [Flash-Z/MCDR-ToDoList#2]
ToDoList1.1.0无法使用!!td add命令修改待办项目（执行后无反应），且使用该命令创建新待办时，错误地提示”已更新“

**Comment by Flash-Z** [comment]
> ToDoList1.1.0无法使用!!td add命令修改待办项目（执行后无反应），且使用该命令创建新待办时，错误地提示”已更新“

草，我马上看看
